import type { Product, Review } from "../types/index.js";

const img = (seed: string, hue: number) =>
  `https://picsum.photos/seed/${seed}/800/600?grayscale`.replace(
    "grayscale",
    `blur=0`,
  ) + `#${hue}`;

function product(partial: Omit<Product, "slug" | "discount" | "createdAt"> & { slug?: string }): Product {
  const discount = Math.max(
    0,
    Math.round(((partial.originalPrice - partial.price) / partial.originalPrice) * 100),
  );
  return {
    ...partial,
    slug: partial.slug ?? partial.name.toLowerCase().replace(/[^a-z0-9]+/g, "-"),
    discount,
    createdAt: "2026-01-15T10:00:00.000Z",
    images: partial.images.length
      ? partial.images
      : [img(partial.id, 20)],
  };
}

export const catalog: Product[] = [
  product({
    id: "p_asus_vivobook15",
    name: "ASUS Vivobook 15 OLED",
    description:
      "A lightweight everyday laptop for coding and college work. 15.6-inch OLED, 16GB RAM and a quiet keyboard make it a strong value pick under ₹70,000.",
    category: "Laptops",
    brand: "ASUS",
    price: 64990,
    originalPrice: 74990,
    rating: 4.5,
    reviewCount: 1284,
    stock: 18,
    specifications: [
      { key: "Processor", value: "Intel Core i5-1335U" },
      { key: "RAM", value: "16GB DDR4" },
      { key: "Storage", value: "512GB SSD" },
      { key: "Display", value: "15.6\" OLED FHD" },
      { key: "Weight", value: "1.70 kg" },
      { key: "Battery", value: "8 hours" },
      { key: "OS", value: "Windows 11 Home" },
    ],
    tags: ["coding", "lightweight", "oled", "value", "student"],
    images: ["https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=1200&q=80"],
    relatedProducts: ["p_logi_m331", "p_stand_alum", "p_backpack_commuter"],
    weightGrams: 1700,
    batteryLifeHours: 8,
    popularity: 96,
  }),
  product({
    id: "p_lenovo_slim3",
    name: "Lenovo IdeaPad Slim 3",
    description:
      "Reliable thin-and-light for developers who want 16GB RAM without crossing a tight budget. Solid build and long battery.",
    category: "Laptops",
    brand: "Lenovo",
    price: 52990,
    originalPrice: 62990,
    rating: 4.3,
    reviewCount: 2102,
    stock: 24,
    specifications: [
      { key: "Processor", value: "AMD Ryzen 5 7530U" },
      { key: "RAM", value: "16GB DDR4" },
      { key: "Storage", value: "512GB SSD" },
      { key: "Display", value: "15.6\" IPS FHD" },
      { key: "Weight", value: "1.63 kg" },
      { key: "Battery", value: "9 hours" },
    ],
    tags: ["coding", "lightweight", "battery", "budget"],
    images: ["https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=1200&q=80"],
    relatedProducts: ["p_keychron_k2", "p_stand_alum"],
    weightGrams: 1630,
    batteryLifeHours: 9,
    popularity: 91,
  }),
  product({
    id: "p_hp_pavilion14",
    name: "HP Pavilion 14",
    description:
      "Compact 14-inch laptop aimed at professionals who travel. Lightweight chassis, bright display, and comfortable typing.",
    category: "Laptops",
    brand: "HP",
    price: 62990,
    originalPrice: 71990,
    rating: 4.4,
    reviewCount: 876,
    stock: 14,
    specifications: [
      { key: "Processor", value: "Intel Core i5-1335U" },
      { key: "RAM", value: "16GB DDR4" },
      { key: "Storage", value: "512GB SSD" },
      { key: "Display", value: "14\" IPS FHD" },
      { key: "Weight", value: "1.41 kg" },
      { key: "Battery", value: "10 hours" },
    ],
    tags: ["lightweight", "coding", "travel", "battery"],
    images: ["https://images.unsplash.com/photo-1511385348-a52b4c57d1d2?auto=format&fit=crop&w=1200&q=80"],
    relatedProducts: ["p_sony_ch720", "p_backpack_commuter"],
    weightGrams: 1410,
    batteryLifeHours: 10,
    popularity: 84,
  }),
  product({
    id: "p_dell_inspiron15",
    name: "Dell Inspiron 15 3530",
    description:
      "A no-nonsense 15-inch laptop for office and college coding. Comfortable keyboard and trustworthy after-sales.",
    category: "Laptops",
    brand: "Dell",
    price: 58490,
    originalPrice: 67990,
    rating: 4.2,
    reviewCount: 1540,
    stock: 20,
    specifications: [
      { key: "Processor", value: "Intel Core i5-1334U" },
      { key: "RAM", value: "16GB DDR4" },
      { key: "Storage", value: "512GB SSD" },
      { key: "Display", value: "15.6\" IPS FHD" },
      { key: "Weight", value: "1.67 kg" },
      { key: "Battery", value: "7 hours" },
    ],
    tags: ["coding", "office", "value"],
    images: ["https://images.unsplash.com/photo-1593642632823-8b857e6f1f18?auto=format&fit=crop&w=1200&q=80"],
    relatedProducts: ["p_logi_k380", "p_logi_m331"],
    weightGrams: 1670,
    batteryLifeHours: 7,
    popularity: 80,
  }),
  product({
    id: "p_acer_aspire5",
    name: "Acer Aspire 5",
    description:
      "Budget coding laptop with a surprisingly good keyboard. Best when the priority is price over polish.",
    category: "Laptops",
    brand: "Acer",
    price: 48990,
    originalPrice: 56990,
    rating: 4.1,
    reviewCount: 990,
    stock: 16,
    specifications: [
      { key: "Processor", value: "AMD Ryzen 5 5500U" },
      { key: "RAM", value: "16GB DDR4" },
      { key: "Storage", value: "512GB SSD" },
      { key: "Display", value: "15.6\" IPS FHD" },
      { key: "Weight", value: "1.80 kg" },
      { key: "Battery", value: "6.5 hours" },
    ],
    tags: ["budget", "coding", "value"],
    images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRkcHnHYna8qnh5VbqFrmq4eQn2b5pdu-sRSMh_563telsjMJqlbtP9S2I&s=10"],
    relatedProducts: ["p_stand_alum"],
    weightGrams: 1800,
    batteryLifeHours: 6.5,
    popularity: 73,
  }),
  product({
    id: "p_asus_tuf15",
    name: "ASUS TUF Gaming F15",
    description:
      "Entry gaming laptop with a dedicated RTX GPU. Handles AAA titles at 1080p and doubles as a sturdy coding machine.",
    category: "Laptops",
    brand: "ASUS",
    price: 69990,
    originalPrice: 84990,
    rating: 4.4,
    reviewCount: 2430,
    stock: 11,
    specifications: [
      { key: "Processor", value: "Intel Core i5-12500H" },
      { key: "RAM", value: "16GB DDR4" },
      { key: "Storage", value: "512GB SSD" },
      { key: "GPU", value: "NVIDIA RTX 3050 4GB" },
      { key: "Display", value: "15.6\" 144Hz FHD" },
      { key: "Weight", value: "2.20 kg" },
      { key: "Battery", value: "5 hours" },
    ],
    tags: ["gaming", "rtx", "coding"],
    images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQsxXK7KJwZNzvP2Cc_IvvCGXNwpRe3zdppAlc4zNKAzw&s=10"],
    relatedProducts: ["p_razer_deathadder", "p_headset_jbl"],
    weightGrams: 2200,
    batteryLifeHours: 5,
    popularity: 94,
  }),
  product({
    id: "p_lenovo_loq",
    name: "Lenovo LOQ 15",
    description:
      "Modern gaming laptop with a cleaner chassis than typical RGB machines. Strong thermals and 16GB RAM.",
    category: "Laptops",
    brand: "Lenovo",
    price: 74990,
    originalPrice: 86990,
    rating: 4.5,
    reviewCount: 1112,
    stock: 9,
    specifications: [
      { key: "Processor", value: "AMD Ryzen 7 7840HS" },
      { key: "RAM", value: "16GB DDR5" },
      { key: "Storage", value: "512GB SSD" },
      { key: "GPU", value: "NVIDIA RTX 4050 6GB" },
      { key: "Display", value: "15.6\" 144Hz FHD" },
      { key: "Weight", value: "2.38 kg" },
      { key: "Battery", value: "5 hours" },
    ],
    tags: ["gaming", "rtx", "performance"],
    images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSwmavcJ9ujZRThzUU0Yd8Ai3riHyayL_UKV7jDsqXKVQ&s=10"],
    relatedProducts: ["p_monitor_samsung27", "p_razer_deathadder"],
    weightGrams: 2380,
    batteryLifeHours: 5,
    popularity: 88,
  }),
  product({
    id: "p_msi_thin",
    name: "MSI Thin GF63",
    description:
      "Slimmer gaming laptop for students who want a GPU without a bulky chassis. Great 144Hz panel.",
    category: "Laptops",
    brand: "MSI",
    price: 67990,
    originalPrice: 79990,
    rating: 4.2,
    reviewCount: 764,
    stock: 8,
    specifications: [
      { key: "Processor", value: "Intel Core i5-12450H" },
      { key: "RAM", value: "16GB DDR4" },
      { key: "Storage", value: "512GB SSD" },
      { key: "GPU", value: "NVIDIA RTX 2050 4GB" },
      { key: "Display", value: "15.6\" 144Hz FHD" },
      { key: "Weight", value: "1.86 kg" },
      { key: "Battery", value: "5.5 hours" },
    ],
    tags: ["gaming", "lightweight", "student"],
    images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTipqzT_UTd6EBD8w8wQ5GerGztZa6HSiwUwqixl1WhRQ&s=10"],
    relatedProducts: ["p_headset_jbl"],
    weightGrams: 1860,
    batteryLifeHours: 5.5,
    popularity: 77,
  }),
  product({
    id: "p_macbook_air_m2",
    name: "Apple MacBook Air 13 M2",
    description:
      "Fanless, silent, and excellent battery. Ideal if you can stretch the budget for build quality and macOS.",
    category: "Laptops",
    brand: "Apple",
    price: 89990,
    originalPrice: 99990,
    rating: 4.8,
    reviewCount: 3210,
    stock: 7,
    specifications: [
      { key: "Processor", value: "Apple M2" },
      { key: "RAM", value: "8GB Unified" },
      { key: "Storage", value: "256GB SSD" },
      { key: "Display", value: "13.6\" Liquid Retina" },
      { key: "Weight", value: "1.24 kg" },
      { key: "Battery", value: "18 hours" },
    ],
    tags: ["lightweight", "battery", "premium", "design"],
    images: ["https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=1200&q=80"],
    relatedProducts: ["p_usbc_hub", "p_stand_alum"],
    weightGrams: 1240,
    batteryLifeHours: 18,
    popularity: 90,
  }),
  product({
    id: "p_hp_victus",
    name: "HP Victus 15",
    description:
      "Balanced gaming laptop with a 144Hz display. Slightly above the ₹70k line, useful as a stretch option.",
    category: "Laptops",
    brand: "HP",
    price: 71990,
    originalPrice: 82990,
    rating: 4.3,
    reviewCount: 688,
    stock: 10,
    specifications: [
      { key: "Processor", value: "AMD Ryzen 5 7535HS" },
      { key: "RAM", value: "16GB DDR5" },
      { key: "Storage", value: "512GB SSD" },
      { key: "GPU", value: "NVIDIA RTX 2050" },
      { key: "Display", value: "15.6\" 144Hz FHD" },
      { key: "Weight", value: "2.29 kg" },
      { key: "Battery", value: "5 hours" },
    ],
    tags: ["gaming", "144hz"],
    images: ["https://images.unsplash.com/photo-1611078489935-0cb964de46d6?auto=format&fit=crop&w=1200&q=80"],
    relatedProducts: ["p_cosmic_kb"],
    weightGrams: 2290,
    batteryLifeHours: 5,
    popularity: 70,
  }),
  product({
    id: "p_galaxy_a35",
    name: "Samsung Galaxy A35 5G",
    description:
      "Clean Android, bright AMOLED, and dependable cameras. A safe all-rounder under ₹30,000.",
    category: "Smartphones",
    brand: "Samsung",
    price: 27999,
    originalPrice: 33999,
    rating: 4.4,
    reviewCount: 4311,
    stock: 30,
    specifications: [
      { key: "Display", value: "6.6\" Super AMOLED 120Hz" },
      { key: "RAM", value: "8GB" },
      { key: "Storage", value: "128GB" },
      { key: "Battery", value: "5000 mAh" },
      { key: "Camera", value: "50MP + 8MP + 5MP" },
    ],
    tags: ["amoled", "value", "camera"],
    images: ["https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=1200&q=80"],
    relatedProducts: ["p_phone_case", "p_screen_glass", "p_charger_65"],
    popularity: 92,
  }),
  product({
    id: "p_redmi_note13",
    name: "Xiaomi Redmi Note 13 Pro",
    description:
      "The value king under ₹25k — 120Hz AMOLED, 67W charging, and a capable 200MP camera.",
    category: "Smartphones",
    brand: "Xiaomi",
    price: 23999,
    originalPrice: 28999,
    rating: 4.3,
    reviewCount: 6120,
    stock: 40,
    specifications: [
      { key: "Display", value: "6.67\" AMOLED 120Hz" },
      { key: "RAM", value: "8GB" },
      { key: "Storage", value: "128GB" },
      { key: "Battery", value: "5100 mAh" },
      { key: "Charging", value: "67W" },
    ],
    tags: ["value", "camera", "charging"],
    images: ["https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?auto=format&fit=crop&w=1200&q=80"],
    relatedProducts: ["p_phone_case", "p_screen_glass"],
    popularity: 97,
  }),
  product({
    id: "p_realme_12pro",
    name: "realme 12 Pro+",
    description:
      "Portrait-first camera phone with a periscope zoom and a curved AMOLED. Fun software, strong specs.",
    category: "Smartphones",
    brand: "realme",
    price: 25999,
    originalPrice: 31999,
    rating: 4.4,
    reviewCount: 1980,
    stock: 22,
    specifications: [
      { key: "Display", value: "6.7\" Curved AMOLED 120Hz" },
      { key: "RAM", value: "8GB" },
      { key: "Storage", value: "256GB" },
      { key: "Battery", value: "5000 mAh" },
      { key: "Camera", value: "50MP periscope" },
    ],
    tags: ["camera", "amoled"],
    images: ["https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=1200&q=80"],
    relatedProducts: ["p_phone_case"],
    popularity: 81,
  }),
  product({
    id: "p_nord_ce4",
    name: "OnePlus Nord CE4",
    description:
      "Clean OxygenOS, 100W charging, and a fluid 120Hz AMOLED. Best software experience under ₹30k.",
    category: "Smartphones",
    brand: "OnePlus",
    price: 24999,
    originalPrice: 26999,
    rating: 4.5,
    reviewCount: 2876,
    stock: 26,
    specifications: [
      { key: "Display", value: "6.7\" AMOLED 120Hz" },
      { key: "RAM", value: "8GB" },
      { key: "Storage", value: "128GB" },
      { key: "Battery", value: "5500 mAh" },
      { key: "Charging", value: "100W" },
    ],
    tags: ["software", "charging", "value"],
    images: ["https://images.unsplash.com/photo-1601784551446-20c9f8ad2d4e?auto=format&fit=crop&w=1200&q=80"],
    relatedProducts: ["p_charger_65", "p_screen_glass"],
    popularity: 89,
  }),
  product({
    id: "p_moto_edge50",
    name: "Motorola Edge 50 Fusion",
    description:
      "Curved pOLED, clean Android, and IP68. Stylish daily driver just under ₹23k.",
    category: "Smartphones",
    brand: "Motorola",
    price: 22999,
    originalPrice: 24999,
    rating: 4.3,
    reviewCount: 1544,
    stock: 19,
    specifications: [
      { key: "Display", value: "6.7\" pOLED 144Hz" },
      { key: "RAM", value: "8GB" },
      { key: "Storage", value: "128GB" },
      { key: "Battery", value: "5000 mAh" },
      { key: "Build", value: "IP68" },
    ],
    tags: ["design", "clean-android", "value"],
    images: ["https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&w=1200&q=80"],
    relatedProducts: ["p_phone_case"],
    popularity: 78,
  }),
  product({
    id: "p_nothing_2a",
    name: "Nothing Phone (2a)",
    description:
      "Unique Glyph interface, clean software, and a distinctive transparent design. Cult favourite under ₹25k.",
    category: "Smartphones",
    brand: "Nothing",
    price: 23999,
    originalPrice: 27999,
    rating: 4.4,
    reviewCount: 3011,
    stock: 15,
    specifications: [
      { key: "Display", value: "6.7\" AMOLED 120Hz" },
      { key: "RAM", value: "8GB" },
      { key: "Storage", value: "128GB" },
      { key: "Battery", value: "5000 mAh" },
    ],
    tags: ["design", "software"],
    images: ["https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?auto=format&fit=crop&w=1200&q=80"],
    relatedProducts: ["p_phone_case", "p_screen_glass"],
    popularity: 86,
  }),
  product({
    id: "p_s23fe",
    name: "Samsung Galaxy S23 FE",
    description:
      "Flagship-adjacent cameras and polish. Over ₹30k, useful when the brief is 'best phone, stretch allowed'.",
    category: "Smartphones",
    brand: "Samsung",
    price: 39999,
    originalPrice: 59999,
    rating: 4.5,
    reviewCount: 2201,
    stock: 12,
    specifications: [
      { key: "Display", value: "6.4\" Dynamic AMOLED 120Hz" },
      { key: "RAM", value: "8GB" },
      { key: "Storage", value: "128GB" },
      { key: "Battery", value: "4500 mAh" },
    ],
    tags: ["premium", "camera", "flagship"],
    images: ["https://images.unsplash.com/photo-1610945415295-d9bbf067b8dd?auto=format&fit=crop&w=1200&q=80"],
    relatedProducts: ["p_phone_case"],
    popularity: 74,
  }),
  product({
    id: "p_iphone13",
    name: "Apple iPhone 13",
    description:
      "Still one of the best cameras and longest software support windows. Premium, but not cheap.",
    category: "Smartphones",
    brand: "Apple",
    price: 49900,
    originalPrice: 59900,
    rating: 4.7,
    reviewCount: 8900,
    stock: 9,
    specifications: [
      { key: "Display", value: "6.1\" Super Retina XDR" },
      { key: "RAM", value: "4GB" },
      { key: "Storage", value: "128GB" },
      { key: "Chip", value: "A15 Bionic" },
    ],
    tags: ["premium", "camera", "ios"],
    images: ["https://images.unsplash.com/photo-1632661674596-df8be070a5c5?auto=format&fit=crop&w=1200&q=80"],
    relatedProducts: ["p_phone_case", "p_airpods"],
    popularity: 85,
  }),
  product({
    id: "p_sony_ch720",
    name: "Sony WH-CH720N",
    description:
      "Light over-ear ANC headphones for commutes and long study sessions. Comfortable for 8+ hour wear.",
    category: "Headphones",
    brand: "Sony",
    price: 8990,
    originalPrice: 14990,
    rating: 4.4,
    reviewCount: 5402,
    stock: 35,
    specifications: [
      { key: "Type", value: "Over-ear wireless" },
      { key: "ANC", value: "Yes" },
      { key: "Battery", value: "35 hours" },
      { key: "Weight", value: "192 g" },
    ],
    tags: ["travel", "anc", "wireless", "wfh"],
    images: ["https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=1200&q=80"],
    relatedProducts: ["p_asus_vivobook15"],
    popularity: 88,
  }),
  product({
    id: "p_boat_550",
    name: "boAt Rockerz 550",
    description:
      "Budget wireless headphones with punchy bass. Fine for casual listening, not for critical work.",
    category: "Headphones",
    brand: "boAt",
    price: 1799,
    originalPrice: 4990,
    rating: 4.1,
    reviewCount: 22100,
    stock: 80,
    specifications: [
      { key: "Type", value: "Over-ear wireless" },
      { key: "Battery", value: "20 hours" },
    ],
    tags: ["budget", "wireless"],
    images: ["https://images.unsplash.com/photo-1484704849700-f032a568e944?auto=format&fit=crop&w=1200&q=80"],
    relatedProducts: [],
    popularity: 79,
  }),
  product({
    id: "p_headset_jbl",
    name: "JBL Tune 770NC",
    description:
      "Adaptive ANC and a fun JBL sound signature. Good WFH and travel pair.",
    category: "Headphones",
    brand: "JBL",
    price: 6499,
    originalPrice: 9999,
    rating: 4.3,
    reviewCount: 1888,
    stock: 28,
    specifications: [
      { key: "Type", value: "Over-ear wireless" },
      { key: "ANC", value: "Adaptive" },
      { key: "Battery", value: "44 hours" },
    ],
    tags: ["anc", "travel", "wfh", "wireless"],
    images: ["https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=1200&q=80"],
    relatedProducts: [],
    popularity: 76,
  }),
  product({
    id: "p_airpods",
    name: "Apple AirPods (2nd Gen)",
    description: "Simple, reliable wireless earbuds if you live in the Apple ecosystem.",
    category: "Headphones",
    brand: "Apple",
    price: 10900,
    originalPrice: 12900,
    rating: 4.5,
    reviewCount: 6700,
    stock: 18,
    specifications: [
      { key: "Type", value: "True wireless" },
      { key: "Battery", value: "5 hours + case" },
    ],
    tags: ["wireless", "ios"],
    images: ["https://images.unsplash.com/photo-1588423771073-b8903fbb85b5?auto=format&fit=crop&w=1200&q=80"],
    relatedProducts: ["p_iphone13"],
    popularity: 72,
  }),
  product({
    id: "p_senn_400",
    name: "Sennheiser HD 400S",
    description: "Wired, honest sound for editing and focused work. No batteries, no pairing.",
    category: "Headphones",
    brand: "Sennheiser",
    price: 4990,
    originalPrice: 6990,
    rating: 4.6,
    reviewCount: 940,
    stock: 21,
    specifications: [
      { key: "Type", value: "Wired on-ear" },
      { key: "Impedance", value: "18 ohm" },
    ],
    tags: ["wired", "studio", "wfh"],
    images: ["https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?auto=format&fit=crop&w=1200&q=80"],
    relatedProducts: [],
    popularity: 61,
  }),
  product({
    id: "p_lg_24",
    name: "LG 24\" IPS Monitor",
    description: "Colour-accurate 24-inch IPS for coding. The extra vertical space pays for itself in a week.",
    category: "Monitors",
    brand: "LG",
    price: 9499,
    originalPrice: 12999,
    rating: 4.4,
    reviewCount: 3102,
    stock: 25,
    specifications: [
      { key: "Size", value: "24 inch" },
      { key: "Panel", value: "IPS" },
      { key: "Resolution", value: "1920x1080" },
      { key: "Refresh", value: "75Hz" },
    ],
    tags: ["wfh", "coding", "ips"],
    images: ["https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=1200&q=80"],
    relatedProducts: ["p_logi_k380", "p_logi_m331"],
    popularity: 83,
  }),
  product({
    id: "p_monitor_samsung27",
    name: "Samsung 27\" Odyssey",
    description: "Larger 27-inch panel for gaming and design. Great pair with a laptop dock.",
    category: "Monitors",
    brand: "Samsung",
    price: 14999,
    originalPrice: 19999,
    rating: 4.5,
    reviewCount: 1766,
    stock: 14,
    specifications: [
      { key: "Size", value: "27 inch" },
      { key: "Panel", value: "IPS" },
      { key: "Resolution", value: "2560x1440" },
      { key: "Refresh", value: "75Hz" },
    ],
    tags: ["wfh", "gaming", "qhd"],
    images: ["https://images.unsplash.com/photo-1593640408182-31c70c8268f5?auto=format&fit=crop&w=1200&q=80"],
    relatedProducts: ["p_asus_tuf15"],
    popularity: 80,
  }),
  product({
    id: "p_dell_24",
    name: "Dell 24\" P2422H",
    description: "Office-grade Dell monitor with a thin bezel and reliable stand. Built for 8-hour days.",
    category: "Monitors",
    brand: "Dell",
    price: 11490,
    originalPrice: 16490,
    rating: 4.6,
    reviewCount: 890,
    stock: 17,
    specifications: [
      { key: "Size", value: "24 inch" },
      { key: "Panel", value: "IPS" },
      { key: "Resolution", value: "1920x1080" },
    ],
    tags: ["wfh", "office"],
    images: ["https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=1200&q=80"],
    relatedProducts: [],
    popularity: 68,
  }),
  product({
    id: "p_logi_k380",
    name: "Logitech K380 Keyboard",
    description: "Compact multi-device Bluetooth keyboard. Switches between laptop, tablet, and phone.",
    category: "Keyboards",
    brand: "Logitech",
    price: 2995,
    originalPrice: 3995,
    rating: 4.5,
    reviewCount: 9800,
    stock: 50,
    specifications: [
      { key: "Type", value: "Wireless compact" },
      { key: "Connectivity", value: "Bluetooth" },
      { key: "Devices", value: "3" },
    ],
    tags: ["wfh", "wireless", "compact"],
    images: ["https://images.unsplash.com/photo-1587829741301-dc798b91add1?auto=format&fit=crop&w=1200&q=80"],
    relatedProducts: ["p_logi_m331"],
    popularity: 87,
  }),
  product({
    id: "p_keychron_k2",
    name: "Keychron K2 Mechanical",
    description: "Hot-swappable mechanical keyboard with mac/win layouts. A joy for long coding sessions.",
    category: "Keyboards",
    brand: "Keychron",
    price: 8999,
    originalPrice: 10999,
    rating: 4.7,
    reviewCount: 2100,
    stock: 13,
    specifications: [
      { key: "Type", value: "Wireless mechanical" },
      { key: "Layout", value: "75%" },
      { key: "Switches", value: "Gateron G Pro" },
    ],
    tags: ["coding", "mechanical", "wfh"],
    images: ["https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?auto=format&fit=crop&w=1200&q=80"],
    relatedProducts: ["p_logi_mx"],
    popularity: 75,
  }),
  product({
    id: "p_cosmic_kb",
    name: "Cosmic Byte CB-GK-16",
    description: "RGB membrane-to-mech budget board for gamers who just need keys that click.",
    category: "Keyboards",
    brand: "Cosmic Byte",
    price: 1799,
    originalPrice: 2499,
    rating: 4.0,
    reviewCount: 4300,
    stock: 42,
    specifications: [
      { key: "Type", value: "Wired gaming" },
      { key: "Lighting", value: "RGB" },
    ],
    tags: ["gaming", "budget"],
    images: ["https://images.unsplash.com/photo-1541140532154-b024d7b8a51?auto=format&fit=crop&w=1200&q=80"],
    relatedProducts: ["p_razer_deathadder"],
    popularity: 66,
  }),
  product({
    id: "p_logi_m331",
    name: "Logitech M331 Silent Mouse",
    description: "Silent click wireless mouse. Ideal for shared apartments and late-night coding.",
    category: "Mice",
    brand: "Logitech",
    price: 1095,
    originalPrice: 1595,
    rating: 4.5,
    reviewCount: 15200,
    stock: 70,
    specifications: [
      { key: "Type", value: "Wireless" },
      { key: "DPI", value: "1000" },
      { key: "Battery", value: "24 months" },
    ],
    tags: ["wfh", "silent", "wireless"],
    images: ["https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&w=1200&q=80"],
    relatedProducts: ["p_stand_alum"],
    popularity: 90,
  }),
  product({
    id: "p_logi_mx",
    name: "Logitech MX Master 3S",
    description: "The productivity mouse. MagSpeed wheel, quiet clicks, and multi-computer flow.",
    category: "Mice",
    brand: "Logitech",
    price: 8995,
    originalPrice: 10995,
    rating: 4.8,
    reviewCount: 4100,
    stock: 16,
    specifications: [
      { key: "Type", value: "Wireless" },
      { key: "DPI", value: "8000" },
      { key: "Connectivity", value: "Bluetooth / Logi Bolt" },
    ],
    tags: ["wfh", "premium", "productivity"],
    images: ["https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=1200&q=80"],
    relatedProducts: ["p_keychron_k2"],
    popularity: 82,
  }),
  product({
    id: "p_razer_deathadder",
    name: "Razer DeathAdder Essential",
    description: "Classic ergonomic gaming mouse. Light, precise, and inexpensive.",
    category: "Mice",
    brand: "Razer",
    price: 3499,
    originalPrice: 4999,
    rating: 4.4,
    reviewCount: 5600,
    stock: 33,
    specifications: [
      { key: "Type", value: "Wired gaming" },
      { key: "DPI", value: "6400" },
    ],
    tags: ["gaming"],
    images: ["https://images.unsplash.com/photo-1629429407756-4a7732138451?auto=format&fit=crop&w=1200&q=80"],
    relatedProducts: ["p_asus_tuf15"],
    popularity: 71,
  }),
  product({
    id: "p_stand_alum",
    name: "Aluminium Laptop Stand",
    description: "Raises the display to eye level and improves cooling. Pairs with any laptop.",
    category: "Accessories",
    brand: "StudioDesk",
    price: 1499,
    originalPrice: 2499,
    rating: 4.4,
    reviewCount: 3200,
    stock: 60,
    specifications: [
      { key: "Material", value: "Aluminium" },
      { key: "Adjustable", value: "Yes" },
    ],
    tags: ["wfh", "bundle", "ergonomics"],
    images: ["https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?auto=format&fit=crop&w=1200&q=80"],
    relatedProducts: ["p_logi_m331"],
    popularity: 84,
  }),
  product({
    id: "p_backpack_commuter",
    name: "Commuter Laptop Backpack",
    description: "Padded 16-inch sleeve, bottle pocket, and a luggage pass-through.",
    category: "Accessories",
    brand: "Northfolk",
    price: 2499,
    originalPrice: 3499,
    rating: 4.3,
    reviewCount: 1400,
    stock: 38,
    specifications: [
      { key: "Capacity", value: "24 L" },
      { key: "Fits", value: "16-inch laptop" },
    ],
    tags: ["travel", "bundle"],
    images: ["https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=1200&q=80"],
    relatedProducts: [],
    popularity: 69,
  }),
  product({
    id: "p_usbc_hub",
    name: "USB-C 7-in-1 Hub",
    description: "HDMI, SD, USB-A and PD passthrough. Essential for modern thin laptops.",
    category: "Accessories",
    brand: "Anker",
    price: 1999,
    originalPrice: 2999,
    rating: 4.5,
    reviewCount: 2600,
    stock: 44,
    specifications: [
      { key: "Ports", value: "HDMI, USB-A x2, SD, PD" },
    ],
    tags: ["wfh", "bundle"],
    images: ["https://images.unsplash.com/photo-1625948515291-69613efd103a?auto=format&fit=crop&w=1200&q=80"],
    relatedProducts: [],
    popularity: 73,
  }),
  product({
    id: "p_webcam",
    name: "1080p Dual-Mic Webcam",
    description: "Crisp video calls without using the laptop camera. Auto light correction.",
    category: "Accessories",
    brand: "Logitech",
    price: 3499,
    originalPrice: 4999,
    rating: 4.4,
    reviewCount: 1990,
    stock: 20,
    specifications: [
      { key: "Resolution", value: "1080p 30fps" },
      { key: "Mic", value: "Dual stereo" },
    ],
    tags: ["wfh", "bundle"],
    images: ["https://images.unsplash.com/photo-1587826080692-f439cd0b70da?auto=format&fit=crop&w=1200&q=80"],
    relatedProducts: [],
    popularity: 64,
  }),
  product({
    id: "p_phone_case",
    name: "Clear Shockproof Phone Case",
    description: "Universal-fit TPU case with raised camera lip. Ships with model insert cards.",
    category: "Accessories",
    brand: "Spigen",
    price: 499,
    originalPrice: 999,
    rating: 4.2,
    reviewCount: 8700,
    stock: 120,
    specifications: [{ key: "Material", value: "TPU" }],
    tags: ["phone", "bundle"],
    images: ["https://images.unsplash.com/photo-1601784551446-20c9f8ad2d4e?auto=format&fit=crop&w=1200&q=80"],
    relatedProducts: ["p_screen_glass"],
    popularity: 93,
  }),
  product({
    id: "p_screen_glass",
    name: "Tempered Glass Screen Protector",
    description: "9H glass with an easy-align tray. Pair with any modern smartphone.",
    category: "Accessories",
    brand: "Spigen",
    price: 299,
    originalPrice: 699,
    rating: 4.1,
    reviewCount: 11200,
    stock: 200,
    specifications: [{ key: "Hardness", value: "9H" }],
    tags: ["phone", "bundle"],
    images: ["https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=1200&q=80"],
    relatedProducts: ["p_phone_case"],
    popularity: 95,
  }),
  product({
    id: "p_charger_65",
    name: "65W GaN USB-C Charger",
    description: "Laptop + phone charging from one brick. Compact enough for a backpack pocket.",
    category: "Accessories",
    brand: "Anker",
    price: 1799,
    originalPrice: 2999,
    rating: 4.6,
    reviewCount: 3400,
    stock: 55,
    specifications: [
      { key: "Power", value: "65W" },
      { key: "Ports", value: "USB-C x2" },
    ],
    tags: ["travel", "wfh", "bundle"],
    images: ["https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=1200&q=80"],
    relatedProducts: [],
    popularity: 81,
  }),
  product({
    id: "p_sdcard",
    name: "SanDisk 128GB Extreme microSD",
    description: "Fast card for cameras, phones, and handhelds. V30 video rated.",
    category: "Accessories",
    brand: "SanDisk",
    price: 899,
    originalPrice: 1499,
    rating: 4.6,
    reviewCount: 7600,
    stock: 48,
    specifications: [
      { key: "Capacity", value: "128GB" },
      { key: "Speed", value: "V30 / U3" },
    ],
    tags: ["camera", "bundle"],
    images: ["https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=1200&q=80"],
    relatedProducts: ["p_tripod"],
    popularity: 67,
  }),
  product({
    id: "p_tripod",
    name: "Compact Travel Tripod",
    description: "Folds to 30cm. Phone + camera mount included.",
    category: "Accessories",
    brand: "Joby",
    price: 1299,
    originalPrice: 2199,
    rating: 4.3,
    reviewCount: 980,
    stock: 27,
    specifications: [
      { key: "Max height", value: "130 cm" },
      { key: "Weight", value: "780 g" },
    ],
    tags: ["camera", "travel", "bundle"],
    images: ["https://images.unsplash.com/photo-1502920917128-1aa500764cbd?auto=format&fit=crop&w=1200&q=80"],
    relatedProducts: ["p_sdcard"],
    popularity: 58,
  }),
];

export const reviewTemplates: Omit<Review, "id" | "productId" | "createdAt">[] = [
  {
    author: "Ananya S.",
    rating: 5,
    title: "Exactly what I needed",
    body: "Battery lasts a full workday and it never felt sluggish for VS Code + Chrome.",
  },
  {
    author: "Rohit K.",
    rating: 4,
    title: "Great value",
    body: "Build is honest for the price. Speakers are average, everything else is solid.",
  },
  {
    author: "Meera P.",
    rating: 5,
    title: "Lightweight winner",
    body: "Took it on two trips already. Charging brick is small enough to forget.",
  },
  {
    author: "Devansh M.",
    rating: 3,
    title: "Good, not perfect",
    body: "Display is nice but the webcam is only okay. Fine if you use an external one.",
  },
];

export const complementaryMap: Record<string, string[]> = {
  Laptops: ["p_stand_alum", "p_logi_m331", "p_backpack_commuter", "p_usbc_hub", "p_logi_k380"],
  Smartphones: ["p_phone_case", "p_screen_glass", "p_charger_65"],
  Headphones: ["p_charger_65"],
  Monitors: ["p_usbc_hub", "p_logi_k380"],
  Keyboards: ["p_logi_m331"],
  Mice: ["p_logi_k380"],
  Accessories: [],
};

export const bundleDiscount = 1200;